# Generated by Django 5.1.6 on 2025-02-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventas',
            name='precio',
        ),
    ]
